### ISSUE TITLE
Mir fails to build with Wayland master, and cmake v3.22.0, linking with wl_proxy_marshal_flags

### ISSUE THREAD

**Issue by n3rdopolis** [canonical/mir#2261]
It oddly builds with v3.20.0
wl_proxy_marshal_flags in Wayland Master caused problems building some other things, but it's odd that this seems to happen with a new version of cmake. 

Below is the error output I get
[100%] Linking CXX executable ../../bin/miral-kiosk.bin
/usr/bin/ld: ../example-server-lib/libexample-shell-lib.a(wayland_shm.cpp.o): in function `WaylandShmBuffer::~WaylandShmBuffer()':
/opt/include/wayland-client-protocol.h:2017: undefined reference to `wl_proxy_marshal_flags'
/usr/bin/ld: ../example-server-lib/libexample-shell-lib.a(wayland_shm.cpp.o): in function `WaylandShm::get_buffer(mir::geometry::Size, mir::geometry::detail::IntWrapper<mir::geometry::StrideTag>)':
/opt/include/wayland-client-protocol.h:1932: undefined reference to `wl_proxy_marshal_flags'
/usr/bin/ld: /opt/include/wayland-client-protocol.h:1371: undefined reference to `wl_proxy_marshal_flags'
/usr/bin/ld: ../example-server-lib/libexample-shell-lib.a(wayland_shm.cpp.o): in function `std::_Sp_counted_ptr_inplace<WaylandShmPool, std::allocator<WaylandShmPool>, (__gnu_cxx::_Lock_policy)2>::_M_dispose()':
/opt/include/wayland-client-protocol.h:1389: undefined reference to `wl_proxy_marshal_flags'
/usr/bin/ld: ../example-server-lib/libexample-shell-lib.a(sw_splash.cpp.o): in function `SwSplash::Self::operator()(wl_display*)':
/opt/include/wayland-client-protocol.h:1038: undefined reference to `wl_proxy_marshal_flags'
/usr/bin/ld: ../example-server-lib/libexample-shell-lib.a(wayland_app.cpp.o):/opt/include/wayland-client-protocol.h:1175: more undefined references to `wl_proxy_marshal_flags' follow
collect2: error: ld returned 1 exit status
make[2]: *** [examples/miral-kiosk/CMakeFiles/miral-kiosk.dir/build.make:124: bin/miral-kiosk.bin] Error 1
make[1]: *** [CMakeFiles/Makefile2:3375: examples/miral-kiosk/CMakeFiles/miral-kiosk.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Linking CXX static library libmiral-spinner.a
[100%] Linking CXX executable ../../bin/mir_demo_server.bin
[100%] Built target miral-spinner
[100%] Built target mir_demo_server
make: *** [Makefile:146: all] Error 2
nerdopolis@nerdopolis:~$

**Comment by n3rdopolis** [comment]
I tested with cmake 3.21.0 and that worked, so it could be a cmake regression in 3.22

**Comment by n3rdopolis** [comment]
Still happening with v3.22.0 since now KDE needs CMake 3.22
Be sure to use the newest libwayland I think the issue must be combined with the CMake version and a change in libwayland, other things around this time had problems with wl_proxy_marshal_flags that were later fixed
